### ISSUE TITLE
Medals dont save for some reason.

### ISSUE THREAD

**Issue by EKT-Goku** [JAJames/Jupiter-Bot#1]
http://renegade-x.com/forums/viewtopic.php?f=119&p=147997#p147997

whole database/ini file is like this

["parasiet"]
Recs=
Noobs=

[Elghinnarisa]
Recs=
Noobs=

["Kassafari"]
Recs=
Noobs=

["mdmx"]
Recs=
Noobs=

**Comment by JAJames** [comment]
Dedicated database file format is presently in the works; all database structures, including medals, will be reworked. I may or may not expand the medals plug-in as well, renaming it back to RenX.LocalLadder.

**Comment by JAJames** [comment]
Forgot to close this -- long fixed.
