### ISSUE TITLE
Can't compile for windows,  stating there are files that are locked or something

### ISSUE THREAD

**Issue by CohenINT** [JAJames/Jupiter-Bot#16]
I cloned the repo,  ran the MakeRelease.bat as admin , started to run and then stopped - displayed a message about elb.dll , something that related to windows search index dll, so i removed that. 
afterward ran the same process again, stopped.  stating that c:\windows\system32\BBI file is locked or busy.  
so eventually It didn't compile into binaries, need assistance .

**Comment by JAJames** [comment]
Not enough information; seems like a setup/environment issue.

Resolved by providing build via Discord.
